services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - demo-network

  api-ordem:
    build:
      context: ./demo-ordem
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - demo-network
  api-processadora:
    build:
      context: ./demo-processador
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - demo-network
  api-notificadora:
    build:
      context: ./demo-notificador
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - demo-network


  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - demo-network
volumes:
  postgres_data:
  rabbitmq_data:

networks:
  demo-network:
    driver: bridge
